spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
---
spring:
  profiles:
    active: local
# ...
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

---
logging:
  level:
    org:
      springframework:
        security: DEBUG
---